version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expenai-server
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./secrets/gcs_key.json:/app/secrets/gcs_key.json
